// Generated by gencpp from file interaccion/multiplicadorResponse.msg
// DO NOT EDIT!


#ifndef INTERACCION_MESSAGE_MULTIPLICADORRESPONSE_H
#define INTERACCION_MESSAGE_MULTIPLICADORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interaccion
{
template <class ContainerAllocator>
struct multiplicadorResponse_
{
  typedef multiplicadorResponse_<ContainerAllocator> Type;

  multiplicadorResponse_()
    : resultado(0)  {
    }
  multiplicadorResponse_(const ContainerAllocator& _alloc)
    : resultado(0)  {
  (void)_alloc;
    }



   typedef int64_t _resultado_type;
  _resultado_type resultado;





  typedef boost::shared_ptr< ::interaccion::multiplicadorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interaccion::multiplicadorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct multiplicadorResponse_

typedef ::interaccion::multiplicadorResponse_<std::allocator<void> > multiplicadorResponse;

typedef boost::shared_ptr< ::interaccion::multiplicadorResponse > multiplicadorResponsePtr;
typedef boost::shared_ptr< ::interaccion::multiplicadorResponse const> multiplicadorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interaccion::multiplicadorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interaccion::multiplicadorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace interaccion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'interaccion': ['/home/xiang/catkin_wsros/src/interaccion/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::interaccion::multiplicadorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaccion::multiplicadorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaccion::multiplicadorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaccion::multiplicadorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaccion::multiplicadorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaccion::multiplicadorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interaccion::multiplicadorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1106c38e6193ae8ef172f60a94e0e0c";
  }

  static const char* value(const ::interaccion::multiplicadorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1106c38e6193ae8ULL;
  static const uint64_t static_value2 = 0xef172f60a94e0e0cULL;
};

template<class ContainerAllocator>
struct DataType< ::interaccion::multiplicadorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interaccion/multiplicadorResponse";
  }

  static const char* value(const ::interaccion::multiplicadorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interaccion::multiplicadorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 resultado\n\
\n\
";
  }

  static const char* value(const ::interaccion::multiplicadorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interaccion::multiplicadorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resultado);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multiplicadorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interaccion::multiplicadorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interaccion::multiplicadorResponse_<ContainerAllocator>& v)
  {
    s << indent << "resultado: ";
    Printer<int64_t>::stream(s, indent + "  ", v.resultado);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERACCION_MESSAGE_MULTIPLICADORRESPONSE_H
