// Generated by gencpp from file interaccion/multiplicadorRequest.msg
// DO NOT EDIT!


#ifndef INTERACCION_MESSAGE_MULTIPLICADORREQUEST_H
#define INTERACCION_MESSAGE_MULTIPLICADORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interaccion
{
template <class ContainerAllocator>
struct multiplicadorRequest_
{
  typedef multiplicadorRequest_<ContainerAllocator> Type;

  multiplicadorRequest_()
    : entrada(0)  {
    }
  multiplicadorRequest_(const ContainerAllocator& _alloc)
    : entrada(0)  {
  (void)_alloc;
    }



   typedef int64_t _entrada_type;
  _entrada_type entrada;





  typedef boost::shared_ptr< ::interaccion::multiplicadorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interaccion::multiplicadorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct multiplicadorRequest_

typedef ::interaccion::multiplicadorRequest_<std::allocator<void> > multiplicadorRequest;

typedef boost::shared_ptr< ::interaccion::multiplicadorRequest > multiplicadorRequestPtr;
typedef boost::shared_ptr< ::interaccion::multiplicadorRequest const> multiplicadorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interaccion::multiplicadorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interaccion::multiplicadorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace interaccion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'interaccion': ['/home/xiang/catkin_wsros/src/interaccion/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::interaccion::multiplicadorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaccion::multiplicadorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaccion::multiplicadorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaccion::multiplicadorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaccion::multiplicadorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaccion::multiplicadorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interaccion::multiplicadorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f84bc19c332ccbd56a70d59a2121c58f";
  }

  static const char* value(const ::interaccion::multiplicadorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf84bc19c332ccbd5ULL;
  static const uint64_t static_value2 = 0x6a70d59a2121c58fULL;
};

template<class ContainerAllocator>
struct DataType< ::interaccion::multiplicadorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interaccion/multiplicadorRequest";
  }

  static const char* value(const ::interaccion::multiplicadorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interaccion::multiplicadorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 entrada\n\
";
  }

  static const char* value(const ::interaccion::multiplicadorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interaccion::multiplicadorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.entrada);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multiplicadorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interaccion::multiplicadorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interaccion::multiplicadorRequest_<ContainerAllocator>& v)
  {
    s << indent << "entrada: ";
    Printer<int64_t>::stream(s, indent + "  ", v.entrada);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERACCION_MESSAGE_MULTIPLICADORREQUEST_H
